version: "3.9"

services:
  automation-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-driven-automation-platform
    ports:
      - "5050:8000"
    environment:
      ENV: dev
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      SERVICENOW_URL: "https://your-instance.service-now.com/api/now/table/incident"
      SERVICENOW_USER: "your_user"
      SERVICENOW_PASSWORD: "your_password"
      SERVICENOW_ENABLED: "false"
    restart: unless-stopped

